version: "3.9"

services:
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./docker/nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/main/static
    ports:
      - 80:80
    depends_on:
      - backend
